kind: pipeline
name: default

workspace:
  path: /home/node/app

steps:
  - name: build
    image: node:14
    volumes:
      - name: yarncache
        path: /root/.cache/yarn
    commands:
      - yarn config set registry https://registry.npmmirror.com
      - yarn
      - yarn build
    environment:
      CI: false

  - name: deploy
    image: node:14
    volumes:
      - name: webroot
        path: /webroot
    commands:
      - mkdir -p /webroot/kiny/
      - rm -rf /webroot/kiny/*
      - cp -rf ./dist/* /webroot/kiny/

volumes:
  - name: webroot
    host:
      path: /root/www
  - name: yarncache
    host:
      path: /root/.yarncache

trigger:
  branch:
    - master
