language: node_js
branches:
  only:
    - master
node_js:
  - "node"

cache: npm

script: npm run build

after_success: 
  - cd ./dist
  - git init
  - git config user.name "${NAME}"
  - git config user.email "${MAIL}"
  - git add .
  - git commit -m "Travis CI 自动构建"
  - git push --force "https://${TOKEN}@${URL}" master

deploy:
skip_cleanup: true
local_dir: dist
on:
  branch: master
