language: node_js
node_js:
  - node
cache: npm

branches:
  only:
    - master

script: npm run build

deploy:
  provider: pages
  skip_cleanup: true
  github_url: ${URL}
  github_token: ${TOKEN}
  keep_history: true
  name: ${NAME}
  email: ${MAIL}
  repo: ${REPO}
  local_dir: dist
  on:
    branch: master
