language: node_js
node_js:
  - "node"

cache: npm

script: npm run build

after_script: 
  - cd ./dist
  - git init
  - git config user.name "${NAME}"
  - git config user.email "${MAIL}"
  - git add .
  - git commit -m "Travis CI 自动构建"
  - git push --force --quiet "https://${TOKEN}@${URL}" master

deploy:
skip_cleanup: true
local_dir: dist
on:
  branch: master